name: Restart PGP
on:
  workflow_dispatch:
  schedule:
    - cron: "15 2 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.PGP_HOST }}
        user: ${{ secrets.PGP_USERNAME }}
        pass: ${{ secrets.PGP_PASSWORD }}
        command: |
          systemctl restart pagermaid_pyro
