name: Run Xray on Serv00
on:
  workflow_dispatch:
  schedule:
    - cron: "15 22 * * *"   # <=== Change this value
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "cache11.serv00.com"
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: "22"
        script: cd xray/ && nohup ./xray -c configserv.json
